"""sleep

Revision ID: 55783f67e942
Revises: b809fc939299
Create Date: 2024-10-09 05:26:06.619518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55783f67e942'
down_revision: Union[str, None] = 'b809fc939299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupa', sa.Column('sleep_time', sa.String(), nullable=True))
    op.add_column('pupa', sa.Column('sleep_state', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_questions', sa.Column('question_type', sa.Enum('music', 'paints', 'history', 'geography', 'mathematics', 'english', 'sport', 'movie', 'games', name='questiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_questions', 'question_type')
    op.drop_column('pupa', 'sleep_state')
    op.drop_column('pupa', 'sleep_time')
    # ### end Alembic commands ###
