"""themes

Revision ID: 9f56134975f2
Revises: 55783f67e942
Create Date: 2024-11-05 18:49:54.836834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f56134975f2'
down_revision: Union[str, None] = '55783f67e942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('themes',
					sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
					sa.Column('theme_name', sa.String(), nullable=False),
					sa.Column('deleted', sa.Boolean(), nullable=False),
					sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
							  nullable=False),
					sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
							  nullable=False),
					sa.PrimaryKeyConstraint('id')
					)
	op.add_column('pupa', sa.Column('sleep_schedule_id', sa.String(), nullable=True))
	op.add_column('questions', sa.Column('theme_id', sa.Integer(), nullable=False))
	op.execute(
		"CREATE TYPE contenttype AS ENUM ('UNKNOWN', 'ANY', 'TEXT', 'ANIMATION', 'AUDIO', 'DOCUMENT', 'PHOTO', 'STICKER', 'VIDEO');")
	content_type = sa.Enum(
		'UNKNOWN', 'ANY', 'TEXT', 'ANIMATION', 'AUDIO', 'DOCUMENT', 'PHOTO', 'STICKER', 'VIDEO',
		name='contenttype',
	)
	op.add_column('questions', sa.Column('media_content_type', content_type, nullable=False))
	op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'])
	op.drop_column('questions', 'question_type')
	op.add_column('user_questions', sa.Column('theme_id', sa.Integer(), nullable=False))
	op.create_foreign_key(None, 'user_questions', 'themes', ['theme_id'], ['id'])
	op.drop_column('user_questions', 'question_type')


# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('user_questions', sa.Column('question_type',
											  postgresql.ENUM('music', 'paints', 'history', 'geography', 'mathematics',
															  'english', 'sport', 'movie', 'games',
															  name='questiontype'), autoincrement=False,
											  nullable=False))
	op.drop_constraint(None, 'user_questions', type_='foreignkey')
	op.drop_column('user_questions', 'theme_id')
	op.add_column('questions', sa.Column('question_type',
										 postgresql.ENUM('music', 'paints', 'history', 'geography', 'mathematics',
														 'english', 'sport', 'movie', 'games', name='questiontype'),
										 autoincrement=False, nullable=False))
	op.drop_constraint(None, 'questions', type_='foreignkey')
	op.drop_column('questions', 'media_content_type')
	op.drop_column('questions', 'theme_id')
	op.drop_column('pupa', 'sleep_schedule_id')
	op.drop_table('themes')
# ### end Alembic commands ###
