"""themes1

Revision ID: f0028528690a
Revises: ea344e00ff83
Create Date: 2024-11-05 19:30:39.905048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0028528690a'
down_revision: Union[str, None] = 'ea344e00ff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'media_content_type',
               existing_type=postgresql.ENUM('UNKNOWN', 'ANY', 'TEXT', 'ANIMATION', 'AUDIO', 'DOCUMENT', 'PHOTO', 'STICKER', 'VIDEO', name='contenttype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'media_content_type',
               existing_type=postgresql.ENUM('UNKNOWN', 'ANY', 'TEXT', 'ANIMATION', 'AUDIO', 'DOCUMENT', 'PHOTO', 'STICKER', 'VIDEO', name='contenttype'),
               nullable=False)
    # ### end Alembic commands ###
